document.writeln("<nav id=\'nav\'>");
document.writeln("		<div id=\'logo\'>");
document.writeln("			<img src=\'img/logo.png\' />");
document.writeln("		</div>");
document.writeln("        <!-- 导航栏 -->  ");
document.writeln("      	<ul id=\'navbar-ul1\'>");
document.writeln("			<li class=\'nav-li underline\' style=\'width: 70px;\'>");
document.writeln("				<a class=\'nav-a\' href=\'index.html\'>首页</a>");
document.writeln("				<span></span>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-li underline\'>");
document.writeln("				<a class=\'nav-a\' href=\'video-tutorial.html\'>视频教程</a>");
document.writeln("				<span></span>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-li underline\'>");
document.writeln("				<a class=\'nav-a\' href=\'getstarted.html\'>入门教程</a>");
document.writeln("				<span></span>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-li underline\'>");
document.writeln("				<a class=\'nav-a\' href=\'community.html\'>社区问答</a>");
document.writeln("				<span></span>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-li underline list\'>");
document.writeln("				<a class=\'nav-a\' href=\'article.html\'>技术文章");
document.writeln("					<i class=\'fa fa-caret-down\' style=\'font-size:24px;color: #afafaf;\'></i>");
document.writeln("				</a>");
document.writeln("				<span></span>");
document.writeln("				<div class=\'drop-down-list\'  style=\'position: absolute;z-index: 3\'>");
document.writeln("					<ul class=\'down-list\'>");
document.writeln("						<li class=\'nav-list\' style=\'margin-top: 5px;\'>");
document.writeln("							<a href=\'article/headlines.html\' target=\'_blank\'>头条&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\' style=\'margin-top: 5px;\'>");
document.writeln("							<a href=\'#\'>博客&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\'>");
document.writeln("							<a href=\'article/phptutorials.html\' target=\'_blank\'>PHP教程</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\'>");
document.writeln("							<a href=\'#\'>HTML教程</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\'>");
document.writeln("							<a href=\'#\'>CSS教程</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-li underline list\'>");
document.writeln("				<a class=\'nav-a\' href=\'resources.html\' target=\'_blank\'>资源下载");
document.writeln("					<i class=\'fa fa-caret-down\' style=\'font-size:24px;color: #afafaf;\'></i>");
document.writeln("				</a>");
document.writeln("				<span></span>");
document.writeln("				<div class=\'drop-down-list\' style=\'position: absolute;z-index: 3\'>");
document.writeln("					<ul class=\'down-list\'>");
document.writeln("						<li class=\'nav-list\' style=\'margin-top: 5px;\'>");
document.writeln("							<a href=\'resources/jsmore.html\' target=\'_blank\'>js特效&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\'  style=\'margin-top: 5px;\'>");
document.writeln("							<a href=\'tool.html\' target=\'_blank\'>PHP工具</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\'>");
document.writeln("							<a href=\'#\'>在线工具&nbsp;&nbsp;</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\'>");
document.writeln("							<a href=\'getstarted.html\'>手册下载</a>");
document.writeln("						</li>");
document.writeln("						<li class=\'nav-list\'>");
document.writeln("							<a href=\'#\'>学习课件&nbsp;&nbsp;</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-li  underline\'>");
document.writeln("				<a class=\'nav-a\' href=\'tool.html\' target=\'_blank\'>工具下载</a>");
document.writeln("				<span></span>");
document.writeln("			</li>");
document.writeln("		</ul>     ");
document.writeln("      <!-- 用户登录栏 -->");
document.writeln("      <ul id=\'navbar-ul2\'>");
document.writeln("         <li class=\'nav-li \' style=\'width:60px;\'><a class=\'nav-a\' href=\'#\'><b>登录</b></a></li>");
document.writeln("        <li class=\'nav-li \' style=\'width:60px;\'><a class=\'nav-a\' href=\'#\'><b>注册</b></a></li>");
document.writeln("      </ul>   ");
document.writeln("    </nav>");
document.writeln("");
document.writeln("    <script src=\'https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js\'></script>");
document.writeln("    <!-- 自定义js -->");
document.writeln("    <script src=\'js/index-js.js\'></script>");