document.writeln("<div class=\'release\'>");
document.writeln("                <a href=\'#\'>发布技术文章</a>");
document.writeln("            </div>");
document.writeln("            <div class=\'headlines\'>");
document.writeln("                <div class=\'title\'>");
document.writeln("                    <span>头条</span>");
document.writeln("                </div>");
document.writeln("                <div class=\'headlines-img\'>");
document.writeln("                    <img src=\'https://img.php.cn/upload/article/000/000/003/5b7399241513d487.png\' />");
document.writeln("                </div>");
document.writeln("                <ul class=\'headlines-nav\'>");
document.writeln("                    <li><a href=\'#\' title=\'鸟哥惠新宸：从Web初学者到PHP核心开发者-2021全球开源技术峰会\'>鸟哥惠新宸：从Web初学者到PHP核心开发者-2021全球开源技术峰会</a></li>");
document.writeln("                    <li><a href=\'#\' title=\'字节跳动常考的基础计算机网络面试题，快来看看！\'>字节跳动常考的基础计算机网络面试题，快来看看！</a></li>");
document.writeln("                    <li><a href=\'#\' title=\'前端框架之争：除了Vue、Angular和React还有谁与之争锋？\'>前端框架之争：除了Vue、Angular和React还有谁与之争锋？</a></li>");
document.writeln("                    <li><a href=\'#\' title=\'推荐一个免费开源的数据库管理开发工具，赶紧下载吧！\'>推荐一个免费开源的数据库管理开发工具，赶紧下载吧！</a></li>");
document.writeln("                    <li><a href=\'#\' title=\'值得收藏的52条提升性能的SQL优化策略\'>值得收藏的52条提升性能的SQL优化策略</a></li>");
document.writeln("                    <li><a href=\'#\' title=\'世上最全的PHP详解（快速入门）\'>世上最全的PHP详解（快速入门）</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class=\'recommend\'>");
document.writeln("                <div class=\'title\'>");
document.writeln("                    <span>推荐视频教程</span>");
document.writeln("                </div>");
document.writeln("                <ul class=\'recommend-nav\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <img src=\'https://img.php.cn/upload/course/000/000/003/5a53132d0bd62424.jpg\' />");
document.writeln("                        </a> ");
document.writeln("                        <span>");
document.writeln("                            <a class=\'link\' href=\'#\'>PHP入门视频教程之一周学会PHP</a>");
document.writeln("                        </span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <img src=\'https://img.php.cn/upload/course/000/000/003/59fd2e510b998327.jpg\' />");
document.writeln("                        </a> ");
document.writeln("                        <span>");
document.writeln("                            <a class=\'link\' href=\'#\'>弹指间学会HTML视频教程</a>");
document.writeln("                        </span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <img src=\'https://img.php.cn/upload/course/000/000/003/59fd2e32e4cb1152.jpg\' />");
document.writeln("                        </a> ");
document.writeln("                        <span>");
document.writeln("                            <a class=\'link\' href=\'#\'>弹指间学会CSS视频教程</a>");
document.writeln("                        </span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <img src=\'https://img.php.cn/upload/course/000/000/003/5a17982d48686254.jpg\' />");
document.writeln("                        </a> ");
document.writeln("                        <span>");
document.writeln("                            <a class=\'link\' href=\'#\'>javascript初级视频教程</a>");
document.writeln("                        </span>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>");
document.writeln("                            <img src=\'https://img.php.cn/upload/course/000/000/003/5a17980f354d0542.jpg\' />");
document.writeln("                        </a> ");
document.writeln("                        <span>");
document.writeln("                            <a class=\'link\' href=\'#\'>CSS3 最新视频教程</a>");
document.writeln("                        </span>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");